# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Junior Conference on Data Science and Engineering
title_short: JDSE
email: ""
description: "Paris-Saclay/IPP Junior Conference on Data Science and Engineering"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jdse-paris.github.io/jDSEParis21/"
meta_author: Jacob Montiel maj 2017 Flora Jay maj 2018 Olivier Fercoq maj 2019 Sylvain Le Corff/Gianluca Quercini 2020 Matthieu Labeau
skills: "Online, 1st-2nd February 2021"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #  url: # http://twitter.com/jekyllrb
  # 2017 twitter page:
  - title: twitter
    url: https://www.twitter.com/JDSEParisSaclay
    share: <a href="https://twitter.com/hashtag/JDSE2021?src=hash"> &#35JDSE2021 </a>
    hashtag: "#JDSE2021"

# Credits content
#credits:
#  <a href="mailto:contact@junior-data-science.org" target="_top">contact@junior-data-science.org</a>

# Build settings
permalink: pretty


# Build settings
plugins:
  - jekyll-feed

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

